import { writeFileSync } from "fs";

export const generateTypesFile = async (
  outputPath: string,
  tableNames: string[]
) => {
  const types = tableNames.map((name) => `  | '${name}'`).join("\n");

  const indexFilePath = `${outputPath}/types.ts`;
  writeFileSync(
    indexFilePath,
    `// This file is auto-generated by zod-pg
// Do not edit this file directly.

export type Table = 
${types};\n`
  );

  console.log(`Generated types file at ${indexFilePath}`);
};
