import { writeFileSync } from "fs";

export const generateConstantsFile = async (
  outputPath: string,
  tableNames: string[]
) => {
  const consts = tableNames
    .map((name) => `export const TABLE_${name.toUpperCase()} = '${name}';`)
    .join("\n");

  const indexFilePath = `${outputPath}/constants.ts`;
  writeFileSync(
    indexFilePath,
    `// This file is auto-generated by zod-pg
// Do not edit this file directly.

${consts}\n`
  );

  console.log(`Generated constants file at ${indexFilePath}`);
};
